views:
  - title: Test environment
    cards:
      - type: 'custom:uptime-card'
        entity: sun.sun
        title:
          show: true
          adaptative_color: true
          style:
            title:
              fontSize: 50px
        icon:
          value:
            ok: mdi:weather-sunny
            ko: mdi:weather-night
          adaptative_color: true
        state:
          value:
            ok: above_horizon
            ko: below_horizon
