views:
  - title: Test environment
    cards:
      - type: 'custom:uptime-card'
        name:
          text: test
          show: true
          adaptative_color: true
        state:
          value: on | off
