views:
  - title: Test environment
    cards:
      - type: 'custom:uptime-card'
        entity: sun.sun
        title:
          text: Test
          show: true
          adaptative_color: true
        state:
          value: above_horizon | below_horizon
